name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # API Key de heroku
          heroku_app_name: 'cachin-test' # Nombre de tu aplicacón
          heroku_email: 'isaac@fintecimal.com' # email que utilizas en heroku
